[project]
name = "aare-temp"
version = "0.1.0"
description = "Aare temperature and flow monitoring dashboard"
requires-python = ">=3.11"
dependencies = [
    "dash",
    "gunicorn",
    "requests",
]

[project.scripts]
aare-temp = "aare_temp.main:main"

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[tool.setuptools.packages.find]
where = ["src"]
